all: breakfast start_driving 

breakfast: cook_eggs make_coffee
	@echo "have breakfast"
	@echo ""

cook_eggs: 
	@echo "cook eggs."
	@echo ""

make_coffee: 
	@echo "make coffee."
	@echo ""

start_driving: find_car_key laptop_in_backpack 
	@echo "start driving to school"
	@echo ""

find_car_key: 
	@echo "find car key. sometimes it's in the fridge."
	@echo ""

laptop_in_backpack: charger_in_backpack 
	@echo "put laptop in the backpack."
	@echo ""

charger_in_backpack:  
	@echo "put laptop charger in the backpack."
	@echo ""
