all: prepare_lunch pack_hiking_gear start_hiking

prepare_lunch: make_sandwich pack_snacks
	@echo "Lunch is ready."
	@echo ""

pack_hiking_gear: fill_water_bottle check_map weather_check
	@echo "All gear is packed for hiking."
	@echo ""

fill_water_bottle:
	@echo "Fill up the water bottle."
	@echo ""

check_map:
	@echo "Check the hiking route map."
	@echo ""

weather_check:
	@echo "Check the weather forecast."
	@echo ""

make_sandwich:
	@echo "Make a sandwich."
	@echo ""

pack_snacks:
	@echo "Pack some snacks."
	@echo ""


start_hiking: put_on_hiking_boots wear_hat apply_sunscreen
	@echo "Start hiking."
	@echo ""

put_on_hiking_boots:
	@echo "Put on hiking boots."
	@echo ""

wear_hat:
	@echo "Wear a hat to block the sun."
	@echo ""

apply_sunscreen:
	@echo "Apply sunscreen to protect from the sun."
	@echo ""
